
package org.oasisopen.sca.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestInvocationService", targetNamespace = "http://test.sca.oasisopen.org/", wsdlLocation = "http://localhost:8080/TestInvocation?wsdl")
public class TestInvocationService
    extends Service
{

    private final static URL TESTINVOCATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.oasisopen.sca.test.TestInvocationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.oasisopen.sca.test.TestInvocationService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/TestInvocation?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/TestInvocation?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESTINVOCATIONSERVICE_WSDL_LOCATION = url;
    }

    public TestInvocationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestInvocationService() {
        super(TESTINVOCATIONSERVICE_WSDL_LOCATION, new QName("http://test.sca.oasisopen.org/", "TestInvocationService"));
    }

    /**
     * 
     * @return
     *     returns TestInvocation
     */
    @WebEndpoint(name = "TestInvocationPort")
    public TestInvocation getTestInvocationPort() {
        return super.getPort(new QName("http://test.sca.oasisopen.org/", "TestInvocationPort"), TestInvocation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestInvocation
     */
    @WebEndpoint(name = "TestInvocationPort")
    public TestInvocation getTestInvocationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test.sca.oasisopen.org/", "TestInvocationPort"), TestInvocation.class, features);
    }

}
