<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * Copyright(C) OASIS(R) 2009, 2010. All Rights Reserved.
 * OASIS trademark, IPR and other policies apply.    
 *   
-->
<!--
 * An example of a WSDL with an xsi:scemaLocation reference to an XSD file
 * Service1z.xsd, that does not exist at the location identified
-->
<wsdl:definitions name="Service1Service" 
targetNamespace="http://test2.sca.oasisopen.org/" 
xmlns:tns="http://test2.sca.oasisopen.org/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:SOAP11="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://test2.sca.oasisopen.org/
   http://example.com/foobar/Service1z.xsd" >
<!-- Above schemaLocation is bogus - no such file exists -->
   <wsdl:message name="operation1Response">
    <wsdl:part name="operation1Response" element="tns:operation1Response">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="operation1">
    <wsdl:part name="operation1" element="tns:operation1">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Service1">
    <wsdl:operation name="operation1">
      <wsdl:input message="tns:operation1">
    </wsdl:input>
      <wsdl:output message="tns:operation1Response">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>

</wsdl:definitions>